<?php
namespace Drupal\resume;

class InfoServiceDecorator extends InfoService {

  public function __construct() {
    parent::__construct();
    return 'Сервис декоратор: InfoServiceDecorator подключен!';
  }

  public function getRandInfo(): string {
    echo 'Сервис декоратор: InfoServiceDecorator подключен!';
    return parent::getRandInfo(); // TODO: Change the autogenerated stub
  }

}
